# Generated by Django 2.2.17 on 2020-12-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_idx', models.PositiveIntegerField(db_index=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'ready'), (5, 'fail')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
