# Generated by Django 2.2.17 on 2021-01-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateUserQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200)),
                ('status', models.SmallIntegerField(choices=[(0, 'ready'), (5, 'fail'), (10, 'progressing')], default=0)),
            ],
            options={
                'verbose_name': 'update_user_queue',
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
