# Generated by Django 2.2.17 on 2021-01-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateuserqueue',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'ready'), (5, 'fail'), (10, 'progressing'), (15, 'success')], default=0),
        ),
    ]
