# Generated by Django 2.2.17 on 2021-02-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repository',
            old_name='language',
            new_name='rep_language',
        ),
        migrations.AddField(
            model_name='repository',
            name='languages',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
