# Generated by Django 2.2.17 on 2020-12-12 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('profile_image', models.CharField(max_length=500, null=True)),
                ('total_contribution', models.IntegerField(db_index=True, default=0, verbose_name='contribution')),
                ('rank', models.SmallIntegerField(choices=[(15, 'Gold'), (10, 'Silver'), (5, 'bronze'), (0, 'unrank')], default=0)),
                ('company', models.CharField(blank=True, default='', max_length=100)),
                ('bio', models.CharField(blank=True, default='', max_length=200)),
                ('blog', models.CharField(blank=True, default='', max_length=100)),
                ('public_repos', models.IntegerField(blank=True, default=0)),
                ('followers', models.IntegerField(blank=True, default=0)),
                ('following', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('contribution', models.IntegerField(db_index=True, default=0, verbose_name='contribution')),
                ('name', models.CharField(max_length=100)),
                ('full_name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='githubs.GithubUser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='githublanguage',
            name='github_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubs.GithubUser'),
        ),
        migrations.DeleteModel(
            name='GithubUserInformation',
        ),
    ]
