# Generated by Django 2.2.17 on 2021-02-14 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0002_auto_20210211_2038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='githubuser',
            old_name='rank',
            new_name='tier',
        ),
    ]
