# Generated by Django 2.2.17 on 2020-12-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0002_auto_20201212_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
                ('logo', models.CharField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='githublanguage',
            name='contribution',
        ),
        migrations.AddField(
            model_name='githublanguage',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='repository',
            name='language',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='language', to='githubs.Language'),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='total_contribution',
            field=models.IntegerField(default=0, verbose_name='contribution'),
        ),
        migrations.AlterField(
            model_name='language',
            name='type',
            field=models.CharField(max_length=100, unique=True, verbose_name='language_type'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='contribution',
            field=models.IntegerField(default=0, verbose_name='contribution'),
        ),
        migrations.CreateModel(
            name='UserOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubs.GithubUser')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='githubs.Organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
