# Generated by Django 2.2.17 on 2020-12-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0003_auto_20201213_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'none'), (5, 'completed'), (10, 'waiting'), (15, 'updating'), (20, 'fail')], default=0),
        ),
        migrations.AlterField(
            model_name='repository',
            name='language',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='github_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_org', to='githubs.GithubUser'),
        ),
        migrations.AlterField(
            model_name='userorganization',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to='githubs.Organization'),
        ),
    ]
