# Generated by Django 2.2.17 on 2020-12-13 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0003_auto_20201213_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'none'), (5, 'completed'), (10, 'waiting'), (15, 'updating'), (20, 'fail')], default=0),
        ),
    ]
