# Generated by Django 2.2.17 on 2021-03-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0004_auto_20210223_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='githubuser',
            name='avatar_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
