# Generated by Django 2.2.17 on 2021-03-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0005_auto_20210303_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='avatar_url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='bio',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='blog',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='company',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
