# Generated by Django 2.2.17 on 2021-03-10 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0006_auto_20210306_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(default=None, max_length=500, null=True, verbose_name='description'),
        ),
    ]
