# Generated by Django 2.2.17 on 2021-07-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0008_auto_20210523_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievements',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='githubuser',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'default_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='githubuser',
            name='user_rank',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='githubuser',
            name='tier',
            field=models.SmallIntegerField(choices=[(35, 'Challenger'), (30, 'Master'), (25, 'Diamond'), (20, 'Platinum'), (15, 'Gold'), (10, 'Silver'), (5, 'Bronze'), (0, 'UnRank')], default=0),
        ),
    ]
