# Generated by Django 2.2.17 on 2021-07-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('githubs', '0009_auto_20210710_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubuser',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
